#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

log() {
  printf '\n[TDDT prepare] %s\n' "$1"
}

warn() {
  printf '\n[TDDT prepare][WARN] %s\n' "$1"
}

detect_arch() {
  uname -m 2>/dev/null || echo "unknown"
}

clean_cmake_cache() {
  local target_dir="$1"

  if [ -d "$target_dir" ]; then
    log "Cleaning stale CMake/build cache in ${target_dir}"
    (
      cd "$target_dir"

      # Remove old CMake build trees and cache files.
      rm -rf build build_updated CMakeCache.txt CMakeFiles

      # Remove stale compiled climate simulator binary that may belong to
      # another architecture, for example x86_64 copied to ARM/aarch64.
      rm -f beef_climate_sim
      rm -f build_updated/beef_climate_sim
    )
  fi
}

clean_python_extensions_for_local_arch() {
  local target_dir="$1"

  if [ -d "$target_dir" ]; then
    log "Cleaning stale Python extension build artifacts in ${target_dir}"
    (
      cd "$target_dir"

      # Remove local build products. This prevents loading old .so files
      # compiled on another machine or architecture.
      rm -rf build

      # Remove compiled Python extension binaries inside packages.
      find . -type f \( -name "*.so" -o -name "*.pyd" -o -name "*.dll" -o -name "*.dylib" \) -print -delete

      # Remove generated Cython C/C++ files only for known local modules if present.
      # They will be regenerated by Cython/setup.py when needed.
      find . -type f \( -name "*.cpython-*.so" -o -name "*.abi3.so" \) -print -delete
    )
  fi
}

log "Starting TDDT preparation"
log "Project root: ${ROOT}"
log "Detected machine architecture: $(detect_arch)"

log "Installing base Python build dependencies"
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools wheel build Cython

log "Installing TDDT Python package and dependencies from pyproject.toml"
python3 -m pip install --no-build-isolation -e "$ROOT"

log "Cleaning stale root-level Python extension artifacts"
rm -rf "$ROOT/build"
find "$ROOT" -maxdepth 3 -type f \( -name "*.cpython-*.so" -o -name "*.abi3.so" \) \
  ! -path "$ROOT/climate_simulator/*" \
  -print -delete || true

log "Compiling TDDT optimizer Cython extensions for local architecture"
python3 setup.py build_ext --inplace

if [ -d "$ROOT/funnel" ]; then
  log "Compiling root-level funnel package for local architecture"
  (
    cd "$ROOT"
    python3 setup.py build_ext --inplace
  )
else
  warn "Root-level funnel directory not found; skipping funnel-specific build step"
fi

log "Preparing climate simulator for local architecture"
clean_python_extensions_for_local_arch "$ROOT/climate_simulator"
clean_cmake_cache "$ROOT/climate_simulator"

log "Installing climate simulator Python package"
(
  cd "$ROOT/climate_simulator"
  python3 -m pip install -e . || {
    warn "Editable install for climate_simulator failed; installing common runtime dependencies instead"
    python3 -m pip install --upgrade cython numpy pandas matplotlib
  }
)

log "Compiling climate simulator Python extension for local architecture"
(
  cd "$ROOT/climate_simulator"
  python3 setup.py build_ext --inplace
)

if command -v cmake >/dev/null 2>&1; then
  log "Configuring and building climate simulator CMake targets for local architecture"
  cmake -S "$ROOT/climate_simulator" -B "$ROOT/climate_simulator/build_updated"
  cmake --build "$ROOT/climate_simulator/build_updated" -j"$(nproc 2>/dev/null || echo 2)"

  if [ -f "$ROOT/climate_simulator/build_updated/beef_climate_sim" ]; then
    log "Checking compiled climate simulator binary"
    file "$ROOT/climate_simulator/build_updated/beef_climate_sim" || true
  else
    warn "CMake build completed, but beef_climate_sim was not found in build_updated"
  fi
else
  warn "cmake not found; skipping CMake binary build for climate_simulator"
  warn "Install cmake on Orange Pi 5 if climate_simulator/main.py requires build_updated/beef_climate_sim"
fi

log "Checking runtime dependencies before long train / work-offline runs"
python3 - <<'PY'
import importlib

missing = []
for name in ["pandas", "numpy", "matplotlib", "Cython"]:
    try:
        importlib.import_module(name)
    except Exception as exc:
        missing.append(f"{name}: {exc}")

if missing:
    raise SystemExit("Missing runtime dependencies:\n" + "\n".join(missing))

print("Runtime dependency check: OK")
PY

log "Creating default optimizer config if needed"
if [ ! -f "$ROOT/optimizer.json" ]; then
  python3 -m tddt_optimizer --config optimizer.json init-config --output optimizer.json
else
  log "optimizer.json already exists; keeping existing user configuration"
fi

log "Ensuring temporary directory from optimizer.json exists"
python3 - <<'PY'
import json
from pathlib import Path

cfg_path = Path("optimizer.json")
if not cfg_path.exists():
    raise SystemExit("optimizer.json not found after init-config")

cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
tmp_dir = Path(cfg.get("tmp_dir", "/tmp/tddt_livestock/"))
tmp_dir.mkdir(parents=True, exist_ok=True)

print(f"tmp_dir ready: {tmp_dir}")
PY

log "Preparing complete dataset for all available rows"
python3 -m tddt_optimizer --config optimizer.json prepare-dataset --growth-start-date 2015-01-01

log "Building CCLL-SEL climate context local library"
python3 -m tddt_optimizer --config optimizer.json prepare-ccll-sel

log "Building SARG-SEL stage-aware growth reference library"
python3 -m tddt_optimizer --config optimizer.json prepare-sarg-sel

log "Final architecture check for climate simulator binary"
if [ -f "$ROOT/climate_simulator/build_updated/beef_climate_sim" ]; then
  file "$ROOT/climate_simulator/build_updated/beef_climate_sim" || true
else
  warn "climate_simulator/build_updated/beef_climate_sim not found"
fi

printf '\nTDDT preparation completed.\n'