# CMake generated Testfile for 
# Source directory: /home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator
# Build directory: /home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke_ifc_probe "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/ifc_probe" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/Building_Information/beef_hall_120.ifc")
set_tests_properties(smoke_ifc_probe PROPERTIES  _BACKTRACE_TRIPLES "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;63;add_test;/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;0;")
add_test(smoke_simulation_csv_mode "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/beef_climate_sim" "--config" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/configs/default_hall.cfg" "--outdoor" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/data/sample_outdoor.csv" "--controls" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/data/sample_controls.csv" "--output" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/smoke_output" "--dt-seconds" "300")
set_tests_properties(smoke_simulation_csv_mode PROPERTIES  _BACKTRACE_TRIPLES "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;65;add_test;/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;0;")
add_test(smoke_simulation_cli_mode "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/beef_climate_sim" "--config" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/configs/default_hall.cfg" "--timestamp" "2026-01-01T00:00:00" "--outdoor-temp-c" "-4" "--outdoor-rh-pct" "78" "--outdoor-wind-m-s" "1.5" "--outdoor-solar-w-m2" "0" "--outdoor-cloud-okta" "4" "--outdoor-rain-mm-day" "0" "--ventilation-group" "20" "--heating-group" "45" "--light-on" "1" "--output" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/smoke_output_cli" "--dt-seconds" "300")
set_tests_properties(smoke_simulation_cli_mode PROPERTIES  _BACKTRACE_TRIPLES "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;74;add_test;/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;0;")
add_test(smoke_herd_inventory_process "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/herd_inventory_cli" "--file" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/herd_inventory.cfg" "--processed" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/herd_inventory_processed.cfg" "--reset")
set_tests_properties(smoke_herd_inventory_process PROPERTIES  _BACKTRACE_TRIPLES "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;91;add_test;/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;0;")
add_test(smoke_herd_inventory_direct_update "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/herd_inventory_cli" "--update-file" "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/build_updated/herd_inventory_processed.cfg" "--summary.cattle_count" "4" "--summary.average_weight_kg" "508.5" "--summary.average_heat_multiplier" "1.415" "--summary.cohort_count" "2" "--cohort" "BxS,495,1.4,1,3" "--cohort" "Hereford,513,1.42,3,3")
set_tests_properties(smoke_herd_inventory_direct_update PROPERTIES  _BACKTRACE_TRIPLES "/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;93;add_test;/home/shabgard/Desktop/DigitalTwin/Trans-DomainDigitalTwinOfCattleFarming/code/tddt_livestock_20260520_1857/climate_simulator/CMakeLists.txt;0;")
